[General]
ScreenWidth="1920"
ScreenHeight="1080"
ScreenPadding="0"

Font="JetBrainsMono Nerd Font"
FontSize="14"
KeyboardSize="0.4"
RoundCorners="10"

Locale=""
HourFormat="HH:mm"
DateFormat="dd/MM/yyyy"

HeaderText="Arch Linux"

BackgroundPlaceholder=""
Background="Backgrounds/default.png"
BackgroundSpeed=""
PauseBackground=""
DimBackground="0.3"
CropBackground="true"
BackgroundHorizontalAlignment="center"
BackgroundVerticalAlignment="center"

HeaderTextColor="#CDD6F4"
DateTextColor="#A6ADC8"
TimeTextColor="#89B4FA"

FormBackgroundColor="#1E1E2E"
BackgroundColor="#1E1E2E"
DimBackgroundColor="#1E1E2E"

LoginFieldBackgroundColor="#313244"
PasswordFieldBackgroundColor="#313244"
LoginFieldTextColor="#CDD6F4"
PasswordFieldTextColor="#CDD6F4"
UserIconColor="#89B4FA"
PasswordIconColor="#89B4FA"

PlaceholderTextColor="#6C7086"
WarningColor="#F38BA8"

LoginButtonTextColor="#1E1E2E"
LoginButtonBackgroundColor="#89B4FA"
SystemButtonsIconsColor="#A6ADC8"
SessionButtonTextColor="#A6ADC8"
VirtualKeyboardButtonTextColor="#A6ADC8"

DropdownTextColor="#CDD6F4"
DropdownSelectedBackgroundColor="#89B4FA"
DropdownBackgroundColor="#313244"

HighlightTextColor="#1E1E2E"
HighlightBackgroundColor="#89B4FA"
HighlightBorderColor="#89B4FA"

HoverUserIconColor="#B4BEFE"
HoverPasswordIconColor="#B4BEFE"
HoverSystemButtonsIconsColor="#B4BEFE"
HoverSessionButtonTextColor="#B4BEFE"
HoverVirtualKeyboardButtonTextColor="#B4BEFE"

PartialBlur="false"
FullBlur="false"
BlurMax="0"
Blur="0"

HaveFormBackground="false"
FormPosition="center"

VirtualKeyboardPosition="center"

HideVirtualKeyboard="true"
HideSystemButtons="false"
HideLoginButton="false"

ForceLastUser="true"
PasswordFocus="true"
HideCompletePassword="true"
AllowEmptyPassword="false"
AllowUppercaseLettersInUsernames="true"
BypassSystemButtonsChecks="false"
RightToLeftLayout="false"

TranslatePlaceholderUsername="Username"
TranslatePlaceholderPassword="Password"
TranslateLogin="Login"
TranslateLoginFailedWarning="Login failed"
TranslateCapslockWarning="Caps Lock is on"
TranslateSuspend="Suspend"
TranslateHibernate="Hibernate"
TranslateReboot="Reboot"
TranslateShutdown="Shutdown"
TranslateSessionSelection="Session"
TranslateVirtualKeyboardButtonOn=""
TranslateVirtualKeyboardButtonOff=""
