
BASE_PACKAGES = [
    "ffmpegthumbnailer", "tumbler",
    "lsd",
    "alacritty",
    "bat",
    "evince",
    "xdotool",
    "mesa", "lib32-mesa", "xf86-video-nouveau", "xf86-video-intel", "vulkan-intel",
    "nvtop",
    "npm",
    "brightnessctl",
    "kitty",
    "gvfs", "gvfs-mtp",
    "automake", "make", "cmake", "autoconf",
    "bluez", "bluez-utils",
    "dunst",
    "fakeroot",
    "feh",
    "firefox",
    "fish",
    "thunar-archive-plugin",
    "gzip", "p7zip", "unrar", "zip", "unzip", "xarchiver",
    "gedit",
    "htop", "btop",
    "thunar",
    "zathura", "zathura-djvu", "zathura-pdf-mupdf",
    "picom",
    "nitrogen",
    "pavucontrol",
    "redshift",
    "scrot",
    "fastfetch",
    "rofi", "rofi-calc", "rofi-emoji",
    "mat2",
    "ranger",
    "calcurse",
    "ttf-jetbrains-mono", "ttf-jetbrains-mono-nerd",
    "ttf-fira-code", "ttf-iosevka-nerd",
    "noto-fonts", "noto-fonts-emoji", "noto-fonts-cjk",
    "libreoffice",
    "tree",
    "sudo",
    "ffmpeg",
    "polybar",
    "torbrowser-launcher",
    "dpkg",
    "gcc", "clang",
    "git",
    "gpick",
    "wget",
    "pamixer",
    "xclip",
    "openvpn",
    "reflector",
    "slop",
    "nano",
    "lxappearance",
    "papirus-icon-theme",
    "imagemagick",
    "ncmpcpp", "mpd", "mpc",
    "mpv",
    "alsa-plugins", "alsa-utils",
    "network-manager-applet", "networkmanager-openvpn",
    "gparted",
    "intel-ucode",
    "gnu-netcat",
    "usbutils",
    "sshfs",
    "netctl",
    "openssh",
    "shellcheck",
    "gthumb",
    "gnome-disk-utility",
    # Audio (pipewire)
    "pipewire", "pipewire-pulse", "wireplumber", "pipewire-alsa",
    # New tools
    "tmux",
    "zoxide",
    "fzf",
    "eza",
    "starship",
    "luarocks",
    "pacman-contrib",
    # SDDM
    "sddm", "qt6-svg", "qt6-declarative", "qt6-5compat",
    # Firewall
    "ufw",
    # Database
    "postgresql",
    # GTK themes
    "catppuccin-gtk-theme-mocha",
]

DEV_PACKAGES = [
    "screenkey",
    "timeshift",
    "pinta",
    "kdenlive",
    "lazygit",
    "wireshark-qt",
    "filezilla",
    "chromium",
    "google-chrome",
    "xfce4-settings",
    "keepassxc",
    "audacity",
    "bleachbit",
    "veracrypt",
    "homebank",
    "neovim",
    "obs-studio",
    "telegram-desktop",
    "yt-dlp",
    "code",
    "cowsay",
    "deluge-gtk",
    "flameshot",
    "sqlitebrowser",
    "obsidian",
    "python-pip",
    "bpython",
    "ipython",
    "cloc",
    "hexyl",
    "cronie",
]

AUR_PACKAGES = [
    "lazydocker",
    "cava",
    "i3lock-color",
    "ptpython",
    "ttf-symbola",
    "hyx",
    "arttime-git",
    "bluetuith",
    "rofi-bluetooth-git",
    "anki",
    "light",
    "catppuccin-cursors-mocha",
    "sddm-astronaut-theme",
]
